package Modelo.dto;
// Generated 22-abr-2020 12:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Administracion generated by hbm2java
 */
public class Administracion  implements java.io.Serializable {


     private Integer idAdministracion;
     private Usuario usuario;
     private String nombre;
     private Set pistas = new HashSet(0);
     private Set competicions = new HashSet(0);
     private Set clasificacionglobals = new HashSet(0);

    public Administracion() {
    }

	
    public Administracion(String nombre) {
        this.nombre = nombre;
    }
    public Administracion(Usuario usuario, String nombre, Set pistas, Set competicions, Set clasificacionglobals) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.pistas = pistas;
       this.competicions = competicions;
       this.clasificacionglobals = clasificacionglobals;
    }
   
    public Integer getIdAdministracion() {
        return this.idAdministracion;
    }
    
    public void setIdAdministracion(Integer idAdministracion) {
        this.idAdministracion = idAdministracion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getPistas() {
        return this.pistas;
    }
    
    public void setPistas(Set pistas) {
        this.pistas = pistas;
    }
    public Set getCompeticions() {
        return this.competicions;
    }
    
    public void setCompeticions(Set competicions) {
        this.competicions = competicions;
    }
    public Set getClasificacionglobals() {
        return this.clasificacionglobals;
    }
    
    public void setClasificacionglobals(Set clasificacionglobals) {
        this.clasificacionglobals = clasificacionglobals;
    }
    



}


