package Modelo.dto;
// Generated 22-abr-2020 12:52:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Competicion generated by hbm2java
 */
public class Competicion  implements java.io.Serializable {


     private Integer idCompeticion;
     private Administracion administracion;
     private Usuario usuario;
     private String formato;
     private Date fechaInicio;
     private Date fechaFin;
     private int npartidos;
     private int nparejas;
     private String nombre;
     private String descripcion;
     private boolean privada;
     private Set partidos = new HashSet(0);
     private Set rankings = new HashSet(0);

    public Competicion() {
    }

	
    public Competicion(String formato, Date fechaInicio, int npartidos, int nparejas, String nombre, String descripcion, boolean privada) {
        this.formato = formato;
        this.fechaInicio = fechaInicio;
        this.npartidos = npartidos;
        this.nparejas = nparejas;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.privada = privada;
    }
    public Competicion(Administracion administracion, Usuario usuario, String formato, Date fechaInicio, Date fechaFin, int npartidos, int nparejas, String nombre, String descripcion, boolean privada, Set partidos, Set rankings) {
       this.administracion = administracion;
       this.usuario = usuario;
       this.formato = formato;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.npartidos = npartidos;
       this.nparejas = nparejas;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.privada = privada;
       this.partidos = partidos;
       this.rankings = rankings;
    }
   
    public Integer getIdCompeticion() {
        return this.idCompeticion;
    }
    
    public void setIdCompeticion(Integer idCompeticion) {
        this.idCompeticion = idCompeticion;
    }
    public Administracion getAdministracion() {
        return this.administracion;
    }
    
    public void setAdministracion(Administracion administracion) {
        this.administracion = administracion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getFormato() {
        return this.formato;
    }
    
    public void setFormato(String formato) {
        this.formato = formato;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public int getNpartidos() {
        return this.npartidos;
    }
    
    public void setNpartidos(int npartidos) {
        this.npartidos = npartidos;
    }
    public int getNparejas() {
        return this.nparejas;
    }
    
    public void setNparejas(int nparejas) {
        this.nparejas = nparejas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isPrivada() {
        return this.privada;
    }
    
    public void setPrivada(boolean privada) {
        this.privada = privada;
    }
    public Set getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set partidos) {
        this.partidos = partidos;
    }
    public Set getRankings() {
        return this.rankings;
    }
    
    public void setRankings(Set rankings) {
        this.rankings = rankings;
    }




}


