package Modelo.dto;
// Generated 22-abr-2020 12:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pareja generated by hbm2java
 */
public class Pareja  implements java.io.Serializable {


     private Integer idPareja;
     private Usuario usuarioByDni2;
     private Usuario usuarioByDni1;
     private String nombre;
     private Set resultadosForIdParejaVisitante = new HashSet(0);
     private Set rankings = new HashSet(0);
     private Set resultadosForIdParejaLocal = new HashSet(0);

    public Pareja() {
    }

	
    public Pareja(String nombre) {
        this.nombre = nombre;
    }
    public Pareja(Usuario usuarioByDni2, Usuario usuarioByDni1, String nombre, Set resultadosForIdParejaVisitante, Set rankings, Set resultadosForIdParejaLocal) {
       this.usuarioByDni2 = usuarioByDni2;
       this.usuarioByDni1 = usuarioByDni1;
       this.nombre = nombre;
       this.resultadosForIdParejaVisitante = resultadosForIdParejaVisitante;
       this.rankings = rankings;
       this.resultadosForIdParejaLocal = resultadosForIdParejaLocal;
    }
   
    public Integer getIdPareja() {
        return this.idPareja;
    }
    
    public void setIdPareja(Integer idPareja) {
        this.idPareja = idPareja;
    }
    public Usuario getUsuarioByDni2() {
        return this.usuarioByDni2;
    }
    
    public void setUsuarioByDni2(Usuario usuarioByDni2) {
        this.usuarioByDni2 = usuarioByDni2;
    }
    public Usuario getUsuarioByDni1() {
        return this.usuarioByDni1;
    }
    
    public void setUsuarioByDni1(Usuario usuarioByDni1) {
        this.usuarioByDni1 = usuarioByDni1;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getResultadosForIdParejaVisitante() {
        return this.resultadosForIdParejaVisitante;
    }
    
    public void setResultadosForIdParejaVisitante(Set resultadosForIdParejaVisitante) {
        this.resultadosForIdParejaVisitante = resultadosForIdParejaVisitante;
    }
    public Set getRankings() {
        return this.rankings;
    }
    
    public void setRankings(Set rankings) {
        this.rankings = rankings;
    }
    public Set getResultadosForIdParejaLocal() {
        return this.resultadosForIdParejaLocal;
    }
    
    public void setResultadosForIdParejaLocal(Set resultadosForIdParejaLocal) {
        this.resultadosForIdParejaLocal = resultadosForIdParejaLocal;
    }




}


