package Modelo.dto;
// Generated 22-abr-2020 12:52:52 by Hibernate Tools 4.3.1



/**
 * Ranking generated by hbm2java
 */
public class Ranking  implements java.io.Serializable {


     private Integer idRanking;
     private Competicion competicion;
     private Pareja pareja;
     private int puntuacion;

    public Ranking() {
    }

	
    public Ranking(int puntuacion) {
        this.puntuacion = puntuacion;
    }
    public Ranking(Competicion competicion, Pareja pareja, int puntuacion) {
       this.competicion = competicion;
       this.pareja = pareja;
       this.puntuacion = puntuacion;
    }
   
    public Integer getIdRanking() {
        return this.idRanking;
    }
    
    public void setIdRanking(Integer idRanking) {
        this.idRanking = idRanking;
    }
    public Competicion getCompeticion() {
        return this.competicion;
    }
    
    public void setCompeticion(Competicion competicion) {
        this.competicion = competicion;
    }
    public Pareja getPareja() {
        return this.pareja;
    }
    
    public void setPareja(Pareja pareja) {
        this.pareja = pareja;
    }
    public int getPuntuacion() {
        return this.puntuacion;
    }
    
    public void setPuntuacion(int puntuacion) {
        this.puntuacion = puntuacion;
    }




}


