package Modelo.dto;
// Generated 22-abr-2020 12:52:52 by Hibernate Tools 4.3.1



/**
 * Resultado generated by hbm2java
 */
public class Resultado  implements java.io.Serializable {


     private Integer idResultado;
     private Pareja parejaByIdParejaVisitante;
     private Pareja parejaByIdParejaLocal;
     private Partido partido;
     private int puntuacionLocal;
     private int puntuacionVisitante;

    public Resultado() {
    }

	
    public Resultado(int puntuacionLocal, int puntuacionVisitante) {
        this.puntuacionLocal = puntuacionLocal;
        this.puntuacionVisitante = puntuacionVisitante;
    }
    public Resultado(Pareja parejaByIdParejaVisitante, Pareja parejaByIdParejaLocal, Partido partido, int puntuacionLocal, int puntuacionVisitante) {
       this.parejaByIdParejaVisitante = parejaByIdParejaVisitante;
       this.parejaByIdParejaLocal = parejaByIdParejaLocal;
       this.partido = partido;
       this.puntuacionLocal = puntuacionLocal;
       this.puntuacionVisitante = puntuacionVisitante;
    }
   
    public Integer getIdResultado() {
        return this.idResultado;
    }
    
    public void setIdResultado(Integer idResultado) {
        this.idResultado = idResultado;
    }
    public Pareja getParejaByIdParejaVisitante() {
        return this.parejaByIdParejaVisitante;
    }
    
    public void setParejaByIdParejaVisitante(Pareja parejaByIdParejaVisitante) {
        this.parejaByIdParejaVisitante = parejaByIdParejaVisitante;
    }
    public Pareja getParejaByIdParejaLocal() {
        return this.parejaByIdParejaLocal;
    }
    
    public void setParejaByIdParejaLocal(Pareja parejaByIdParejaLocal) {
        this.parejaByIdParejaLocal = parejaByIdParejaLocal;
    }
    public Partido getPartido() {
        return this.partido;
    }
    
    public void setPartido(Partido partido) {
        this.partido = partido;
    }
    public int getPuntuacionLocal() {
        return this.puntuacionLocal;
    }
    
    public void setPuntuacionLocal(int puntuacionLocal) {
        this.puntuacionLocal = puntuacionLocal;
    }
    public int getPuntuacionVisitante() {
        return this.puntuacionVisitante;
    }
    
    public void setPuntuacionVisitante(int puntuacionVisitante) {
        this.puntuacionVisitante = puntuacionVisitante;
    }




}


