package Modelo.dto;
// Generated 22-abr-2020 12:52:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String dni;
     private String nombreCompleto;
     private String usuario;
     private String clave;
     private String email;
     private String sexo;
     private String rol;
     private String categoria;
     private String ladoDeJuego;
     private String fotoPerfil;
     private Set partidos = new HashSet(0);
     private Set administracions = new HashSet(0);
     private Set competicions = new HashSet(0);
     private Set parejasForDni2 = new HashSet(0);
     private Set parejasForDni1 = new HashSet(0);
     private Set clasificacionglobals = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String dni, String nombreCompleto, String usuario, String clave, String email, String sexo, String rol) {
        this.dni = dni;
        this.nombreCompleto = nombreCompleto;
        this.usuario = usuario;
        this.clave = clave;
        this.email = email;
        this.sexo = sexo;
        this.rol = rol;
    }
    
    public Usuario(String dni, String nombreCompleto, String usuario, String clave, String email, String sexo, String rol, String fotoPerfil) {
        this.dni = dni;
        this.nombreCompleto = nombreCompleto;
        this.usuario = usuario;
        this.clave = clave;
        this.email = email;
        this.sexo = sexo;
        this.rol = rol;
        this.fotoPerfil = fotoPerfil;
    }
    
    public Usuario(String dni, String nombreCompleto, String usuario, String clave, String email, String sexo, String rol, String categoria, String ladoDeJuego) {
        this.dni = dni;
        this.nombreCompleto = nombreCompleto;
        this.usuario = usuario;
        this.clave = clave;
        this.email = email;
        this.sexo = sexo;
        this.rol = rol;
        this.categoria = categoria;
        this.ladoDeJuego = ladoDeJuego;
    }
    
    public Usuario(String dni, String nombreCompleto, String usuario, String clave, String email, String sexo, String rol, String categoria, String ladoDeJuego, String fotoPerfil) {
        this.dni = dni;
        this.nombreCompleto = nombreCompleto;
        this.usuario = usuario;
        this.clave = clave;
        this.email = email;
        this.sexo = sexo;
        this.rol = rol;
        this.categoria = categoria;
        this.ladoDeJuego = ladoDeJuego;
        this.fotoPerfil = fotoPerfil;
    }
    
    public Usuario(String dni, String nombreCompleto, String usuario, String clave, String email, String sexo, String rol, String categoria, String ladoDeJuego, String fotoPerfil, Set partidos, Set competicions, Set parejasForDni2, Set parejasForDni1, Set clasificacionglobals) {
       this.dni = dni;
       this.nombreCompleto = nombreCompleto;
       this.usuario = usuario;
       this.clave = clave;
       this.email = email;
       this.sexo = sexo;
       this.rol = rol;
       this.categoria = categoria;
       this.ladoDeJuego = ladoDeJuego;
       this.fotoPerfil = fotoPerfil;
       this.partidos = partidos;
       this.competicions = competicions;
       this.parejasForDni2 = parejasForDni2;
       this.parejasForDni1 = parejasForDni1;
       this.clasificacionglobals = clasificacionglobals;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getLadoDeJuego() {
        return this.ladoDeJuego;
    }
    
    public void setLadoDeJuego(String ladoDeJuego) {
        this.ladoDeJuego = ladoDeJuego;
    }
    public String getFotoPerfil() {
        return this.fotoPerfil;
    }
    
    public void setFotoPerfil(String fotoPerfil) {
        this.fotoPerfil = fotoPerfil;
    }
    public Set getPartidos() {
        return this.partidos;
    }
    
    public void setPartidos(Set partidos) {
        this.partidos = partidos;
    }
    public Set getAdministracions() {
        return this.administracions;
    }
    
    public void setAdministracions(Set administracions) {
        this.administracions = administracions;
    }
    public Set getCompeticions() {
        return this.competicions;
    }
    
    public void setCompeticions(Set competicions) {
        this.competicions = competicions;
    }
    public Set getParejasForDni2() {
        return this.parejasForDni2;
    }
    
    public void setParejasForDni2(Set parejasForDni2) {
        this.parejasForDni2 = parejasForDni2;
    }
    public Set getParejasForDni1() {
        return this.parejasForDni1;
    }
    
    public void setParejasForDni1(Set parejasForDni1) {
        this.parejasForDni1 = parejasForDni1;
    }
    public Set getClasificacionglobals() {
        return this.clasificacionglobals;
    }
    
    public void setClasificacionglobals(Set clasificacionglobals) {
        this.clasificacionglobals = clasificacionglobals;
    }




}


